name: Secrets and Variables

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04

    env:
      DEPLOYMENT_ENV: 'production'  # Define a workflow-level environment variable

    steps:
    - name: Build
      run: |
        # Build your application here
        echo "Building the application"
      env:
        SECRET_API_KEY: ${{ secrets.API_KEY }}  # Access a secret as an environment variable
        CONFIG_VARIABLE: ${{ env.DEPLOYMENT_ENV }}  # Use a workflow-level environment variable
        ANOTHER_VARIABLE: 'Some value'  # Define a variable directly in the workflow

    - name: Deploy
      run: |
        # Deploy your application using the secrets and variables
        echo "Deploying the application to ${CONFIG_VARIABLE} environment"
        echo "Secret print ${{ secrets.API_KEY }}"
        echo "Github's variable ${{ vars.USERNAME }}"
        echo "Step's variable ${SECRET_API_KEY}"
      env:
        SECRET_API_KEY: ${{ secrets.API_KEY }}
