name: 07 Passing Files In Artifacts
on:
  workflow_dispatch:
    
jobs:
  unit-tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout source code 
        uses: actions/checkout@v4
      - name: Install Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install tox
        run: pip install tox
      - name: Run unit tests
        run: |
          cd backend
          tox -e unit
          # Verificar que o arquivo .coverage existe
          ls -la .coverage
          # Como o arquivo está aqui, precisamos copiá-lo para um local acessível no próximo step
          cp .coverage ../coverage-file
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage-file  # Arquivo copiado no step anterior
  
  load-file-example:
    runs-on: ubuntu-22.04
    needs: [unit-tests]
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: coverage
          path: ${{ github.workspace }}
      - name: List folder 
        run: ls -la ${{ github.workspace }}