name: 07 Passing Files In Artifacts

on:
  workflow_dispatch:
    
jobs:
  unit-tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout source code 
        uses: actions/checkout@v4

      - name: Install Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install tox
          pip install pytest-cov  # Certifique-se que o pytest-cov está instalado

      - name: Run unit tests with coverage
        run: |
          cd backend
          # Gera o coverage explicitamente
          python -m pytest --cov=. --cov-report= tests/
          # Verifica onde o .coverage foi gerado
          find . -name ".coverage" -type f
          ls -la

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: backend/.coverage


  load-file-example:
    runs-on: ubuntu-22.04
    needs: [unit-tests]
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: coverage

      - name: Show downloaded files
        run: |
          ls -la
          ls -la coverage/