name: Example CI

on:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout source code 
        uses: actions/checkout@v4
      - name: Install Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install tox
        run: pip install tox
      - name: Run lint
        run: |
          cd backend
          tox -e lint
  
  unit-test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout source code 
        uses: actions/checkout@v4
      - name: Install Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install tox
        run: pip install tox
      - name: Run lint
        run: |
          cd backend
          tox -e unit

  build-image:
    runs-on: ubuntu-22.04
    needs: [lint, unit-test]  # Specify that build-image depends on lint and unit-test
    steps:
      - name: Checkout source code 
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and export
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: misohu/fast-api-example:latest
          outputs: type=docker,dest=/tmp/fast-api-example.tar
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: fast-api-example
          path: /tmp/fast-api-example.tar
  
  integration-tests:
    runs-on: ubuntu-22.04
    needs: [build-image]
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: fast-api-example
          path: /tmp
      - name: Load image
        run: |
          docker load --input /tmp/myimage.tar
          docker image ls -a 