name: 07 Passing Files In Artifacts

on:
  workflow_dispatch:
    
jobs:
  unit-tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout source code 
        uses: actions/checkout@v4

      - name: Install Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          cd backend
          pip install -e .  # Instala o pacote em modo desenvolvimento
          pip install tox pytest-cov fastapi pytest  # Instala dependências explicitamente

      - name: Run tests with coverage
        run: |
          cd backend
          python -m pytest --cov=. --cov-report= tests/
          ls -la .coverage  # Verifica se o arquivo foi criado

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: backend/.coverage

  load-file-example:
    runs-on: ubuntu-22.04
    needs: [unit-tests]
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: coverage

      - name: Show downloaded files
        run: |
          ls -la
          ls -la coverage/