name: 07 Passing Files In Artifacts

on:
  workflow_dispatch:
    
jobs:
  unit-tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout source code 
        uses: actions/checkout@v4

      - name: Install Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install tox
        run: pip install tox
        
      - name: Run unit tests
        run: |
          cd backend
          tox -e unit
          # Verifica explicitamente se o arquivo .coverage foi criado
          ls -la .coverage || echo "Arquivo .coverage não encontrado"
          pwd  # Mostra o diretório atual para debug

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: backend/.coverage  # Caminho relativo ao workspace
  
  load-file-example:
    runs-on: ubuntu-22.04
    needs: [unit-tests]
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: coverage

      - name: List folder 
        run: |
          ls -la
          ls -la coverage/