name: Build with Functions

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Variables
        id: set-vars
        run: echo "MESSAGE=Hello, World!\nFILE_CONTENT=This is the content of the file." >> $GITHUB_ENV

      - name: Use contains function
        run: |
          if echo "${{ env.MESSAGE }}" | grep -q "Hello"; then
            echo "Message contains 'Hello'"
          else
            echo "Message does not contain 'Hello'"
          fi

      - name: Use startsWith function
        run: |
          if [[ "${{ env.FILE_CONTENT }}" == This* ]]; then
            echo "File content starts with 'This'"
          else
            echo "File content does not start with 'This'"
          fi

      - name: Use endsWith function
        run: |
          if [[ "${{ env.FILE_CONTENT }}" == *file. ]]; then
            echo "File content ends with 'file.'"
          else
            echo "File content does not end with 'file.'"
          fi

      - name: Use format function
        run: |
          FORMATTED_MESSAGE=$(echo "Formatted: ${{ env.MESSAGE }}")
          echo "${FORMATTED_MESSAGE}"

      - name: Use join function
        run: |
          ARRAY=("Item1" "Item2" "Item3")
          JOINED=$(IFS=,; echo "${ARRAY[*]}")
          echo "Joined array: ${JOINED}"

      - name: Use toJSON and fromJSON functions
        run: |
          ORIGINAL_ARRAY=("Item1" "Item2" "Item3")
          JSON_ARRAY=$(echo "${ORIGINAL_ARRAY[@]}" | jq -c -R .)
          CONVERTED_ARRAY=($(echo "${JSON_ARRAY}" | jq -r -c 'split("\n")' | tr -d '[]," '))
          echo "Original array: ${ORIGINAL_ARRAY[@]}"
          echo "Converted array: ${CONVERTED_ARRAY[@]}"

      - name: Use hashFiles function
        run: |
          HASH=$(find . -type f -exec sha256sum {} + | sort -k 2 | sha256sum | cut -d ' ' -f 1)
          echo "Hash of all files: ${HASH}"
