name: Functions Demo

on:
  push:
    branches:
      - main

jobs:
  demo:
    runs-on: ubuntu-latest

    env:
      MESSAGE: 'Hello, World!'
      FILE_CONTENT: 'This is the content of the file.'
      ARRAY: ('element1', 'element2', 'element3')
      TEST_JSON_DATA: '{"status": "amazing"}'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Create Sample File
        run: |
          echo ${{ env.FILE_CONTENT }} > sample.txt
          cat sample.txt

      - name: Use contains function
        run: | 
          echo "${{ contains('Hello', env.MESSAGE) }}"

      - name: Use startsWith function
        run: | 
          echo "${{ startsWith('This', env.FILE_CONTENT) }}"

      - name: Use endsWith function
        run: | 
          echo "${{ endsWith('file.', env.FILE_CONTENT) }}"

      - name: Use format function
        run: | 
          echo "${{ format('Formatted: {0}', env.MESSAGE) }}"

      - name: Use join function
        run: | 
          echo "${{ join(', ', env.ARRAY) }}"

      - name: Use toJSON function
        run: |
          echo "${{ toJSON(env.TEST_JSON_DATA) }}"

      - name: Use fromJSON function
        run: |
          ORIGINAL_ARRAY=("Item1" "Item2" "Item3")
          JSON_ARRAY=${{ toJSON(env.TEST_JSON_DATA) }}
          CONVERTED_ARRAY=$(fromJSON "${JSON_ARRAY}")
          echo "Original array: ${ORIGINAL_ARRAY[@]}"
          echo "Converted array: ${CONVERTED_ARRAY[@]}"

      - name: Use hashFiles function
        run: |
          echo "Hash of all files: ${{ hashFiles('**') }}"
